CREATE DATABASE IF NOT EXISTS pwiki_prod;
USE pwiki_prod;
CREATE TABLE documents (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(45) NOT NULL,
    type VARCHAR(45) NOT NULL,
    descr LONGTEXT NOT NULL,
    link TEXT NOT NULL,
    changed_at VARCHAR(45) NOT NULL
)